# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/georgian_support;


"/software/packages"=pkg_repl("basesystem","10.0-3","noarch");
"/software/packages"=pkg_repl("bash","4.1.7-3.fc14","x86_64");
"/software/packages"=pkg_repl("bpg-algeti-fonts","2.005-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-chveulebrivi-fonts","3.002-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-courier-fonts","4.002-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-courier-s-fonts","4.000-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-elite-fonts","3.000-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-excelsior-fonts","2.025-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-fonts-common","20090205-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-glaho-fonts","9.000-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-ingiri-fonts","4.000-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-nino-medium-cond-fonts","4.005-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-nino-medium-fonts","4.005-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-sans-fonts","1.005-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-sans-medium-fonts","1.005-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-sans-modern-fonts","2.025-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-sans-regular-fonts","1.005-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-serif-fonts","1.005-7.fc12","noarch");
"/software/packages"=pkg_repl("bpg-serif-modern-fonts","2.028-7.fc12","noarch");
"/software/packages"=pkg_repl("dejavu-fonts-common","2.32-1.fc14","noarch");
"/software/packages"=pkg_repl("dejavu-sans-fonts","2.32-1.fc14","noarch");
"/software/packages"=pkg_repl("dejavu-sans-mono-fonts","2.32-1.fc14","noarch");
"/software/packages"=pkg_repl("dejavu-serif-fonts","2.32-1.fc14","noarch");
"/software/packages"=pkg_repl("filesystem","2.4.35-1.fc14","x86_64");
"/software/packages"=pkg_repl("fontpackages-filesystem","1.44-1.fc14","noarch");
"/software/packages"=pkg_repl("glibc","2.12.90-17",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12.90-17","x86_64");
"/software/packages"=pkg_repl("libgcc","4.5.1-4.fc14","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-8.20100703.fc14","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-8.20100703.fc14","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.7-6.fc14","x86_64");
"/software/packages"=pkg_repl("setup","2.8.23-1.fc14","noarch");
"/software/packages"=pkg_repl("tzdata","2010k-1.fc14","noarch");

