# Template generated by comps2pan.xsl - DO NOT EDIT
#
# 
#

unique template rpms/kashubian_support;


"/software/packages"=pkg_repl("basesystem","10.0-3","noarch");
"/software/packages"=pkg_repl("bash","4.1.7-3.fc14","x86_64");
"/software/packages"=pkg_repl("filesystem","2.4.35-1.fc14","x86_64");
"/software/packages"=pkg_repl("glibc","2.12.90-17",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12.90-17","x86_64");
"/software/packages"=pkg_repl("hunspell","1.2.12-1.fc14","x86_64");
"/software/packages"=pkg_repl("hunspell-csb","0.20050311-4.fc12","noarch");
"/software/packages"=pkg_repl("libgcc","4.5.1-4.fc14","x86_64");
"/software/packages"=pkg_repl("libstdc++","4.5.1-4.fc14","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-8.20100703.fc14","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-8.20100703.fc14","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.7-6.fc14","x86_64");
"/software/packages"=pkg_repl("setup","2.8.23-1.fc14","noarch");
"/software/packages"=pkg_repl("tzdata","2010k-1.fc14","noarch");

