# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Support for cross-compiling programs to 32 bit Windows targets, testing them, and building installers, all from within Fedora.
#

unique template rpms/mingw32;



