# Template generated by comps2pan.xsl - DO NOT EDIT
#
# Support for developing programs in the Perl programming language.
#

unique template rpms/perl;


'/software/packages'=pkg_repl('perl-Readonly','1.03-13.fc14','noarch');
'/software/packages'=pkg_repl('perl-Net-LibIDN','0.12-4.fc14','x86_64');
'/software/packages'=pkg_repl('perl-Net-SMTP-SSL','1.01-5.fc14','noarch');
'/software/packages'=pkg_repl('perl-Crypt-SSLeay','0.58-1.fc14','x86_64');
'/software/packages'=pkg_repl('perl-DBI','1.613-1.fc14','x86_64');
'/software/packages'=pkg_repl('perl-IO-String','1.08-10.fc14','noarch');
'/software/packages'=pkg_repl('perl-Proc-ProcessTable','0.44-6.fc14','x86_64');
'/software/packages'=pkg_repl('perl-Readonly-XS','1.05-5.fc14','x86_64');

