# Template generated by comps2pan.xsl - DO NOT EDIT
#
# These packages are helpful when developing web applications or web pages.
#

unique template rpms/web_development;


"/software/packages"=pkg_repl("Django","1.2.3-1.fc14","noarch");
"/software/packages"=pkg_repl("audit-libs","2.0.4-4.fc14","x86_64");
"/software/packages"=pkg_repl("basesystem","10.0-3","noarch");
"/software/packages"=pkg_repl("bash","4.1.7-3.fc14","x86_64");
"/software/packages"=pkg_repl("bzip2-libs","1.0.6-1.fc14.1","x86_64");
"/software/packages"=pkg_repl("ca-certificates","2010.63-3.fc14","noarch");
"/software/packages"=pkg_repl("coreutils","8.5-6.fc14","x86_64");
"/software/packages"=pkg_repl("coreutils-libs","8.5-6.fc14","x86_64");
"/software/packages"=pkg_repl("cracklib","2.8.16-4.fc14","x86_64");
"/software/packages"=pkg_repl("cracklib-dicts","2.8.16-4.fc14","x86_64");
"/software/packages"=pkg_repl("db4","4.8.30-2.fc14","x86_64");
"/software/packages"=pkg_repl("expat","2.0.1-10.fc13","x86_64");
"/software/packages"=pkg_repl("filesystem","2.4.35-1.fc14","x86_64");
"/software/packages"=pkg_repl("gdbm","1.8.3-6.fc14","x86_64");
"/software/packages"=pkg_repl("glibc","2.12.90-17",PKG_ARCH_GLIBC);
"/software/packages"=pkg_repl("glibc-common","2.12.90-17","x86_64");
"/software/packages"=pkg_repl("gmp","4.3.1-7.fc14","x86_64");
"/software/packages"=pkg_repl("grep","2.7-1.fc14.1","x86_64");
"/software/packages"=pkg_repl("gzip","1.4-1.fc14","x86_64");
"/software/packages"=pkg_repl("info","4.13a-10.fc14","x86_64");
"/software/packages"=pkg_repl("keyutils-libs","1.2-6.fc12","x86_64");
"/software/packages"=pkg_repl("krb5-libs","1.8.2-6.fc14","x86_64");
"/software/packages"=pkg_repl("less","436-6.fc14","x86_64");
"/software/packages"=pkg_repl("libacl","2.2.49-8.fc14","x86_64");
"/software/packages"=pkg_repl("libattr","2.4.44-5.fc14","x86_64");
"/software/packages"=pkg_repl("libcap","2.17-1.fc13","x86_64");
"/software/packages"=pkg_repl("libcom_err","1.41.12-5.fc14","x86_64");
"/software/packages"=pkg_repl("libffi","3.0.9-1.fc13","x86_64");
"/software/packages"=pkg_repl("libgcc","4.5.1-4.fc14","x86_64");
"/software/packages"=pkg_repl("libselinux","2.0.96-5.fc14","x86_64");
"/software/packages"=pkg_repl("libsepol","2.0.41-3.fc14","x86_64");
"/software/packages"=pkg_repl("libstdc++","4.5.1-4.fc14","x86_64");
"/software/packages"=pkg_repl("ncurses","5.7-8.20100703.fc14","x86_64");
"/software/packages"=pkg_repl("ncurses-base","5.7-8.20100703.fc14","x86_64");
"/software/packages"=pkg_repl("ncurses-libs","5.7-8.20100703.fc14","x86_64");
"/software/packages"=pkg_repl("nss-softokn-freebl","3.12.7-6.fc14","x86_64");
"/software/packages"=pkg_repl("openssl","1.0.0a-2.fc14",PKG_ARCH_OPENSSL);
"/software/packages"=pkg_repl("pam","1.1.1-5.fc14","x86_64");
"/software/packages"=pkg_repl("pcre","8.10-1.fc14","x86_64");
"/software/packages"=pkg_repl("python","2.7-8.fc14.1","x86_64");
"/software/packages"=pkg_repl("python-libs","2.7-8.fc14.1","x86_64");
"/software/packages"=pkg_repl("python-simplejson","2.1.1-3.fc14","x86_64");
"/software/packages"=pkg_repl("readline","6.1-2.fc14","x86_64");
"/software/packages"=pkg_repl("setup","2.8.23-1.fc14","noarch");
"/software/packages"=pkg_repl("sqlite","3.6.23.1-1.fc14","x86_64");
"/software/packages"=pkg_repl("tzdata","2010k-1.fc14","noarch");
"/software/packages"=pkg_repl("zlib","1.2.5-2.fc14","x86_64");

